### ISSUE TITLE
x.match is not a function

### ISSUE THREAD

**Issue by janchlebek** [dvejsada/PID_integration#26]
Hi, I recently updated the integration and as expected my dashboard had issues (using Flex table card).
I corrected all entities  but even then I just get an error message instead of the table that says _x.match is not a function_  
Any ideas? I only modify the stop name and entities with wildcard.
Flex card yaml looks like this:
```yaml
type: custom:flex-table-card
title:
  - Černý Most
entities:
  include:
    - sensor.cerny_most_15_next_route_name_*
columns:
  - data: departure_timestamp.scheduled
    name: TIME
    modify: x.match(/[0-9]{2}:[0-9]{2}/);
  - data: state
    name: LINE
  - data: trip.headsign
    name: DESTINATION
  - data: delay
    name: DELAY
    modify: |-
      if (x.is_available){
        x.minutes + " min."
      } else {
        "-"
      };
```
Any ideas?
